### ISSUE TITLE
Libs only working after renaming

### ISSUE THREAD

**Issue by LudiusMaximus** [hnsteyding/files#1]
Thanks for compiling and uploading.
However, your libaacs-0.dll and libbdplus-0.dll are only recognised by VLC after I renamed them to libaacs.dll and libbdplus.dll.
Is this on purpose?

**Comment by hnsteyding** [comment]
Yes.
I have now added a README for that.

**Comment by LudiusMaximus** [comment]
Cool, thank you. Can you say what benefits to expect when using your compiled files instead of the ones provided by the link in this post? https://forum.doom9.org/showthread.php?p=1886086

**Comment by hnsteyding** [comment]
There was a request from user "Balling" if it's possible to compile these libraries from the latest source:
[https://forum.doom9.org/showthread.php?p=2000214#post2000214](https://forum.doom9.org/showthread.php?p=2000214#post2000214)

As far as I know, the latest sources already contain the mentioned patches.
